### ISSUE TITLE
Game doesn't load properly. 

### ISSUE THREAD

**Issue by Setharious** [harbingerofme/Bepinex.Monomod.HookGenPatcher#13]
When using this mod with the newest version of risk of rain 2 it causes the camera to appear in a random location out of bounds on the first stage and the player character doesn't load in though enemies are still visible and working.

This got closed for some reason, and the response was that it was something dependent on hookgenpatcher, but I only have hookgenpatcher and BepInExPack enabled. If I turn off hookgenpatcher, then BepInExPack works fine on its own. Enabling only hookgenpatcher, and nothing else, causes the weird camera angle and inability to play. Can mods that are not enabled really cause problems?

**Comment by harbingerofme** [comment]
If you can provide a log file, I'll look into it, but as stated before in other issues: hookgenpatcher is a general multigame patcher that sinply provides an abstraction layer to run monomod's hookgen during the patcher pahae of BepInEx. It's supplied with a configuration for the specific pieces for the risk of rain 2 community **on thunderstore**. So most likely it's an issue with that configuration (raise this issue in their discord) or with hookgen itself, in which case I'll escalate it. 

However: no log. No support

**Comment by legokidlogan** [comment]
I was able to narrow this down to being an issue caused by two deprecated mods for making [printers](https://thunderstore.io/package/TheRealElysium/Faster3DPrinters/) and [scrappers](https://thunderstore.io/package/jenwalter/FasterScrapper/) faster, *not* caused by HGP itself. Fortunately, [ExchangeChanges](https://thunderstore.io/package/Flyingcomputer/Exchange_Changes/) exists to replace those mods, and works fine.

There's not much point anymore hunting down the bug in those two mods, let alone in this repo, but here's the log anyway if you're still curious:
```
[Error: Unity Log] FileNotFoundException: Could not load file or assembly 'UnityEngine.Networking, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
DMD<>?-1285780480.Hook<RoR2.Stage::Start>?1988294016 (RoR2.Stage ) (at <e9103647d5e047eabac088cb7841e0b6>:0)
```
